### ISSUE TITLE
DomainException with message 'OpenSSL unable to sign data'

### ISSUE THREAD

**Issue by vino-jasuba** [cdoco/php-jwt#12]
I'm trying to use the jwt_encode() function to create a jwt ... I have supplied the payload, a private key and specified the algorithm to use as 'RS256' ... but I keep getting the above exception. I have spent hours googling what the issue could be but I'm getting nowhere. Please help

**Comment by cdoco** [comment]
What's your version of OpenSSL? show me your execute scripts, Including public and private keys.

**Comment by cdoco** [comment]
`PHP Warning: jwt_decode(): aud type must be array in Psy Shell code on line 1`

Audience type must be array :

```
$payload = [
    'data' => 'data',
    'aud' => ['Young', 'Old']
];

$token = jwt_encode($payload, $privateKey,  'RS256');
print_r(jwt_decode($token, $publicKey, ['algorithm' => 'RS256']));
```

**Comment by vino-jasuba** [comment]
so what do I do with a token that decodes to a json document with an aud type of a string .... like this one here 


eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJUTG80bE81dVNZRktfNGRPQ0l1NDg0YTN5dG13M3U4SlFYWlNqRFNESFI4In0.eyJqdGkiOiIxYjU0ODJhMS1mN2ZkLTRhZDAtYTA1Mi0zMzA2ODIzNjc3ZDciLCJleHAiOjE1MzE2NTc0MDcsIm5iZiI6MCwiaWF0IjoxNTMxNjU2ODA3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvdWp1enkiLCJhdWQiOiJ1anV6eV9hcGkiLCJzdWIiOiJmZmIxZjQ4ZC04NGI3LTQ3ODYtODc4Zi1kZGQ1ZDVhNDlkM2EiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJ1anV6eV9hcGkiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJhYmI2N2ZlYS04NmIwLTRmM2YtOWE2ZS00OGE5ODk1MDQ1ODkiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwibmFtZSI6IkthcnVnYSBUZXJlc2lhIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzcyIsImdpdmVuX25hbWUiOiJLYXJ1Z2EiLCJmYW1pbHlfbmFtZSI6IlRlcmVzaWEiLCJlbWFpbCI6ImthcnVnYUBnbWFpbC5jb20ifQ.OfI6HmrKAk33rpWvCAsnfAG5KLhp8cF0J9pwpdYKdHTKReCBIdr1fD3lItHDzbqhuN9-vB7ebcQPQ1hA1Lx_Q_e31F0Azqb_GlcdLD9cKUJTSiiM5OC6f1g_BZA_jBKoosjZGNDoSmsUYKK9FKmfvpefzr2jPBi_ZYOOGLHJUJIdLkdJZHtdNzR9r9WBfAwfBoqJKTHjWX9HAShrUjwBD7J2vNJBimDUMlexuFohCmVcD3iRr3fdfMqQ61kqpe8XjjwhEi1E0GLkqJ59-HqaKujt0aIskUuCTKHPd938XYsQ2som3o544K53SZAVWCQy-9c0-Meb4BSe0X-NmKqoSg


which decodes to 


{
  "jti": "1b5482a1-f7fd-4ad0-a052-3306823677d7",
  "exp": 1531657407,
  "nbf": 0,
  "iat": 1531656807,
  "iss": "http://localhost:8080/auth/realms/ujuzy",
  "aud": "ujuzy_api",
  "sub": "ffb1f48d-84b7-4786-878f-ddd5d5a49d3a",
  "typ": "Bearer",
  "azp": "ujuzy_api",
  "auth_time": 0,
  "session_state": "abb67fea-86b0-4f3f-9a6e-48a989504589",
  "acr": "1",
  "allowed-origins": [],
  "realm_access": {
    "roles": [
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "name": "Karuga Teresia",
  "preferred_username": "tess",
  "given_name": "Karuga",
  "family_name": "Teresia",
  "email": "karuga@gmail.com"
}

**Comment by cdoco** [comment]
The string type is not supported at present, I will add string type support to the next version. 

you can use it like this right now:

```
{
    "aud": ["ujuzy_api"],
}
```

**Comment by vino-jasuba** [comment]
That'll be great. Thanks
