### ISSUE TITLE
如何静态编译？

### ISSUE THREAD

**Issue by patrickkh7788** [cdoco/php-jwt#15]
在特殊换下需要静态编译php（例如docker环境)。

一般其他库是放在php的ext目录下，删除configure, 运行 ./buildconf --force 。

再次执行configure --help就有了  --enable-jwt类似的选项。

php-jwt库里就没有 --enable-jwt，在静态编译的时候无法启用。

**Comment by patrickkh7788** [comment]
另外benchmark的图，点开放大了都看不清数字。是否可以优化下。

**Comment by cdoco** [comment]
我最近会加上对 `--enable-jwt` 静态编译的支持。

图片看不清的问题，我会尽量优化下，谢谢支持呀。
