### ISSUE TITLE
mac can't compile

### ISSUE THREAD

**Issue by kissIce** [cdoco/php-jwt#17]
my mac can‘t complie.   configure: error: Please reinstall the OpenSSL library  .    how can I fix it?

**Comment by cdoco** [comment]
This extension depends on **OpenSSL (Version >= 1.0.1f)**, you can check if it has been installed. `openssl version`, or use this command to see `ls -al /usr/local/include/openssl/hmac.h`.

If you do not install OpenSSL, can use brew to install `brew install openssl`.

**Comment by kissIce** [comment]
think,  I have solve it
