### ISSUE TITLE
exp time bug

### ISSUE THREAD

**Issue by kissIce** [cdoco/php-jwt#18]
I find a bug in php-cli mode.   if code run in php-cli mode, the exp time can't valid.   I think may be the C function to get time have problem .  example: I use swoft  framework and I have add middleware to valid token , and I set exp is time() + 10 . but 30 second after .it also can use

**Comment by kissIce** [comment]
<?php
$hmackey = 123456;
$payload = ['data' => 'data', 'exp' => time() +10];

// build expired token
$token = jwt_encode($payload, $hmackey, 'HS256');

try{
    $decoded_token = jwt_decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjoiZGF0YSIsImV4cCI6MTU0MTIzNTYyMX0.yGQFos2HNgGat400NcRqTMxmkSvOY8BmlGf-P0r17Wo', $hmackey, [ 'algorithm' => 'HS256']);
}catch (ExpiredSignatureException $e)
{
    echo 1;
}


if build expired token ,then it can't thow exception.   but if annotation build expired token .then it can  thow exception.   like this:


<?php
//$hmackey = 123456;
//$payload = ['data' => 'data', 'exp' => time() +10];
//
//// build expired token
//$token = jwt_encode($payload, $hmackey, 'HS256');

try{
    $decoded_token = jwt_decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjoiZGF0YSIsImV4cCI6MTU0MTIzNTYyMX0.yGQFos2HNgGat400NcRqTMxmkSvOY8BmlGf-P0r17Wo', $hmackey, [ 'algorithm' => 'HS256']);
}catch (ExpiredSignatureException $e)
{
    echo 1;
}

**Comment by cdoco** [comment]
This is a bug. I fixed this problem in the `develop` branch. You can switch to  `develop` branch and recompile the extension. It should be available.
